version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Node.js dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build
artifacts:
  files:
    - '**/*'

