version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build phase...
  post_build:
    commands:
      - echo Post build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
